# Generated by Django 5.0 on 2024-02-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0004_newuser_token_created_at_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='mobilenumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
