# Generated by Django 5.0 on 2024-02-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0005_newuser_mobilenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='forgot_password_token',
            new_name='Forgot_password_token',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='mobilenumber',
            new_name='MobileNumber',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='token_created_at',
            new_name='Token_created_at',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='username',
            new_name='Username',
        ),
    ]
